# global.R --------------------------------------------------------------------
library(shiny)
library(shinydashboard)
library(shinyjs)
library(shinycssloaders)
library(DT)
library(ggplot2)
library(dplyr)
library(mgcv)
library(readr)
